#!/usr/bin/env python3
import json
from collections import defaultdict
from common import REPO

ROOT = REPO
RESEARCH = ROOT / "docs/research"
DATA_OUT = ROOT / "data/ores.json"
CATALOG_OUT = ROOT / "docs/ore-catalog.md"

GROUPS = {
    "ferrous-ferroalloy": "Ferrous & Ferroalloy Metals",
    "base-metals": "Base Metals",
    "industrial-minerals": "Industrial & Non-Metal Minerals",
    "light-battery-tech": "Light, Battery & Tech Metals",
    "precious-pgm": "Precious Metals & PGMs",
    "rare-earths": "Rare Earth Elements",
    "minor-specialty": "Minor, Specialty & Radioactive Metals",
}

STAGE_ORDER = [
    "Crushing", "Grinding", "Washing", "Screening",
    "GravitySeparation", "MagneticSeparation", "ElectrostaticSeparation", "FrothFlotation",
    "Decrepitation", "Roasting", "Volatilization", "Calcination", "Sintering",
    "Chlorination", "Cracking",
    "Smelting", "Converting",
    "CarbothermicReduction", "AluminothermicReduction", "SilicothermicReduction",
    "MetallothermicReduction", "HydrogenReduction", "Reduction", "KrollProcess",
    "Leaching", "PressureOxidation", "BioOxidation", "Dissolution",
    "SolventExtraction", "IonExchange", "CarbonAdsorption",
    "Precipitation", "Evaporation", "Crystallization",
    "Electrowinning", "Electrolysis", "HallHeroult", "MoltenSaltElectrolysis",
    "ChlorAlkali", "Electrorefining",
    "BayerProcess", "SolvayProcess", "ContactProcess", "ClausProcess",
    "FraschProcess", "SiemensProcess", "Cupellation", "Retorting",
    "Refining", "Purification", "Alloying",
]


def main():
    ores = [{**entry, "group": slug} for slug in GROUPS
            for entry in json.loads((RESEARCH / f"{slug}.json").read_text(encoding="utf-8"))]

    used, qualified = set(), set()
    byproduct_sources = defaultdict(set)
    for e in ores:
        for stage in e.get("stages", []):
            base = stage.split("(", 1)[0].strip()
            used.add(base)
            if base not in STAGE_ORDER:
                qualified.add(stage)
        for bp in e.get("byproducts", []):
            byproduct_sources[bp].add(e["mineral"])
    vocab = [s for s in STAGE_ORDER if s in used]

    DATA_OUT.write_text(json.dumps({
        "_generated_by": "tools/build_catalog.py",
        "_source": "docs/research/*.json",
        "groups": GROUPS,
        "stageVocabulary": vocab,
        "oreCount": len(ores),
        "ores": ores,
    }, indent=2, ensure_ascii=False), encoding="utf-8")

    md = []
    md.append("# Ore & Material Catalog\n")
    md.append("> Generated by `tools/build_catalog.py` from `docs/research/*.json`. "
              "Do not edit by hand — edit the per-group research files and regenerate.\n")
    md.append(f"**{len(ores)} ore/mineral entries** across {len(GROUPS)} commodity groups. "
              "Each real-world chain runs raw mineral → beneficiation → intermediate → "
              "metal/product, using the canonical processing-stage vocabulary below so every "
              "chain maps cleanly onto in-game machines.\n")

    md.append("## Processing-stage vocabulary\n")
    md.append("Ordered roughly by position in a real flowsheet:\n")
    md.append(" · ".join(f"`{s}`" for s in vocab) + "\n")
    if qualified:
        md.append("_Stages used with qualifiers not in the base vocabulary: "
                  + ", ".join(f"`{s}`" for s in sorted(qualified)) + "._\n")

    for slug, title in GROUPS.items():
        rows = [e for e in ores if e["group"] == slug]
        if not rows:
            continue
        md.append(f"## {title}\n")
        md.append(f"_{len(rows)} entries · detailed notes in "
                  f"[`docs/research/{slug}.md`](research/{slug}.md)_\n")
        md.append("| Mineral | Formula | Commodity | Byproducts | Chain (stages) | Final product |")
        md.append("|---|---|---|---|---|---|")
        for e in rows:
            bp = ", ".join(e.get("byproducts", [])) or "—"
            stages = " → ".join(e.get("stages", [])) or "—"
            md.append(
                f"| {e.get('mineral','')} | `{e.get('formula','')}` | "
                f"{e.get('commodity','')} | {bp} | {stages} | {e.get('final_product','')} |"
            )
        md.append("")

    md.append("## Byproduct cross-links\n")
    md.append("Elements recovered as byproducts (→ the minerals that yield them). "
              "This is the realistic web that makes certain elements gated behind others:\n")
    md.append("| Byproduct | Recovered from |")
    md.append("|---|---|")
    for bp in sorted(byproduct_sources):
        md.append(f"| {bp} | {', '.join(sorted(byproduct_sources[bp]))} |")
    md.append("")

    CATALOG_OUT.write_text("\n".join(md), encoding="utf-8")

    print(f"ores: {len(ores)}")
    for slug in GROUPS:
        print(f"  {slug}: {sum(e['group'] == slug for e in ores)}")
    print(f"commodities: {len({e.get('commodity', '?') for e in ores})}")
    print(f"stages used: {len(used)} ({len(vocab)} in vocab)")
    if qualified:
        print(f"  qualified/extra stages: {sorted(qualified)}")
    print(f"byproduct elements tracked: {len(byproduct_sources)}")
    print(f"wrote {DATA_OUT.relative_to(ROOT)} and {CATALOG_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
